filter:
    excluded_paths:
        - 'tests/*'
        - 'examples/*'
checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php:
            version: 7.0.12