language: php
php:
  - '5.3.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-nightly
before_script:
  - composer install --prefer-source
  - cp phpunit.xml.dist phpunit.xml
